version: "3"
services:
  database:
    container_name: database
    build:
      context: .
      dockerfile: ./db/Dockerfile
    restart: always
    environment:
      POSTGRES_DB: carturesti
      POSTGRES_USER: carturar
      POSTGRES_PASSWORD: parolacarturar
    ports:
      - "2000:5432"
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
  ui:
    container_name: ui
    build:
      context: .
      dockerfile: ./ui/Dockerfile
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - database
