version: "3"
services:
  database:
    container_name: database
    build:
      context: .
      dockerfile: ./db/Dockerfile
    restart: always
    environment:
      POSTGRES_DB: carturesti
      POSTGRES_USER: carturar
      POSTGRES_PASSWORD: parolacarturar
    ports:
      - "2000:5432"
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
  user-management-api:
    container_name: user-management-api
    build:
      context: .
      dockerfile: ./user-management-api/Dockerfile
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - database
  stock-management-api:
    container_name: stock-management-api
    build:
      context: .
      dockerfile: ./stock-management-api/Dockerfile
    command: "php artisan serve --host=0.0.0.0"
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - database
  ui:
    container_name: ui
    build:
      context: .
      dockerfile: ./ui/Dockerfile
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - user-management-api
