version: "3"
services:
  database:
    container_name: database
    build:
      context: .
      dockerfile: ./db/Dockerfile
    restart: always
    environment:
      POSTGRES_DB: carturesti
      POSTGRES_USER: carturar
      POSTGRES_PASSWORD: parolacarturar
    ports:
      - "2000:5432"
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
