--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1 (Debian 16.1-1.pgdg120+1)
-- Dumped by pg_dump version 16.1

-- Started on 2023-12-19 20:58:52 EET

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 6 (class 2615 OID 16385)
-- Name: carturesti_mic; Type: SCHEMA; Schema: -; Owner: carturar
--

CREATE SCHEMA carturesti_mic;


ALTER SCHEMA carturesti_mic OWNER TO carturar;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 227 (class 1259 OID 24644)
-- Name: addresses; Type: TABLE; Schema: carturesti_mic; Owner: carturar
--

CREATE TABLE carturesti_mic.addresses (
    id integer NOT NULL,
    city character varying(512) NOT NULL,
    county character varying(512) NOT NULL,
    country character varying(512) NOT NULL,
    address_line character varying(512) NOT NULL
);


ALTER TABLE carturesti_mic.addresses OWNER TO carturar;

--
-- TOC entry 226 (class 1259 OID 24643)
-- Name: addresses_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE carturesti_mic.addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 24615)
-- Name: auth; Type: TABLE; Schema: carturesti_mic; Owner: carturar
--

CREATE TABLE carturesti_mic.auth (
    id integer NOT NULL,
    token character varying(512) NOT NULL,
    user_id integer
);


ALTER TABLE carturesti_mic.auth OWNER TO carturar;

--
-- TOC entry 220 (class 1259 OID 24614)
-- Name: auth_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE carturesti_mic.auth ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.auth_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 24636)
-- Name: authors; Type: TABLE; Schema: carturesti_mic; Owner: carturar
--

CREATE TABLE carturesti_mic.authors (
    id integer NOT NULL,
    name character varying(512) NOT NULL
);


ALTER TABLE carturesti_mic.authors OWNER TO carturar;

--
-- TOC entry 224 (class 1259 OID 24635)
-- Name: authors_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE carturesti_mic.authors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.authors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 24652)
-- Name: books; Type: TABLE; Schema: carturesti_mic; Owner: carturar
--

CREATE TABLE carturesti_mic.books (
    id integer NOT NULL,
    title character varying(512) NOT NULL,
    price integer,
    genre_id integer,
    quantity integer
);


ALTER TABLE carturesti_mic.books OWNER TO carturar;

--
-- TOC entry 231 (class 1259 OID 24665)
-- Name: books_authors; Type: TABLE; Schema: carturesti_mic; Owner: carturar
--

CREATE TABLE carturesti_mic.books_authors (
    id integer NOT NULL,
    book_id integer NOT NULL,
    author_id integer NOT NULL
);


ALTER TABLE carturesti_mic.books_authors OWNER TO carturar;

--
-- TOC entry 230 (class 1259 OID 24664)
-- Name: books_authors_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE carturesti_mic.books_authors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.books_authors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 24651)
-- Name: books_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE carturesti_mic.books ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.books_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 24715)
-- Name: favourite_books; Type: TABLE; Schema: carturesti_mic; Owner: carturar
--

CREATE TABLE carturesti_mic.favourite_books (
    id integer NOT NULL,
    book_id integer,
    user_id integer
);


ALTER TABLE carturesti_mic.favourite_books OWNER TO carturar;

--
-- TOC entry 236 (class 1259 OID 24714)
-- Name: favourite_books_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE carturesti_mic.favourite_books ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.favourite_books_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 24628)
-- Name: genres; Type: TABLE; Schema: carturesti_mic; Owner: carturar
--

CREATE TABLE carturesti_mic.genres (
    id integer NOT NULL,
    name character varying(512) NOT NULL
);


ALTER TABLE carturesti_mic.genres OWNER TO carturar;

--
-- TOC entry 222 (class 1259 OID 24627)
-- Name: genres_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE carturesti_mic.genres ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.genres_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 24577)
-- Name: migrations; Type: TABLE; Schema: carturesti_mic; Owner: carturar
--

CREATE TABLE carturesti_mic.migrations (
    id integer NOT NULL,
    "timestamp" bigint NOT NULL,
    name character varying NOT NULL
);


ALTER TABLE carturesti_mic.migrations OWNER TO carturar;

--
-- TOC entry 216 (class 1259 OID 24576)
-- Name: migrations_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: carturar
--

CREATE SEQUENCE carturesti_mic.migrations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE carturesti_mic.migrations_id_seq OWNER TO carturar;

--
-- TOC entry 3458 (class 0 OID 0)
-- Dependencies: 216
-- Name: migrations_id_seq; Type: SEQUENCE OWNED BY; Schema: carturesti_mic; Owner: carturar
--

ALTER SEQUENCE carturesti_mic.migrations_id_seq OWNED BY carturesti_mic.migrations.id;


--
-- TOC entry 235 (class 1259 OID 24699)
-- Name: order_products; Type: TABLE; Schema: carturesti_mic; Owner: carturar
--

CREATE TABLE carturesti_mic.order_products (
    id integer NOT NULL,
    order_id integer,
    book_id integer,
    quantity integer
);


ALTER TABLE carturesti_mic.order_products OWNER TO carturar;

--
-- TOC entry 234 (class 1259 OID 24698)
-- Name: order_products_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE carturesti_mic.order_products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.order_products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 24681)
-- Name: orders; Type: TABLE; Schema: carturesti_mic; Owner: carturar
--

CREATE TABLE carturesti_mic.orders (
    id integer NOT NULL,
    user_id integer NOT NULL,
    total integer NOT NULL,
    creation_date timestamp without time zone,
    status character varying(512) NOT NULL,
    address_id integer
);


ALTER TABLE carturesti_mic.orders OWNER TO carturar;

--
-- TOC entry 232 (class 1259 OID 24680)
-- Name: orders_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE carturesti_mic.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 24606)
-- Name: users; Type: TABLE; Schema: carturesti_mic; Owner: carturar
--

CREATE TABLE carturesti_mic.users (
    id integer NOT NULL,
    email character varying(512) NOT NULL,
    first_name character varying(512) NOT NULL,
    last_name character varying(512) NOT NULL,
    password character varying(512) NOT NULL,
    is_admin boolean DEFAULT false NOT NULL
);


ALTER TABLE carturesti_mic.users OWNER TO carturar;

--
-- TOC entry 218 (class 1259 OID 24605)
-- Name: users_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE carturesti_mic.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3254 (class 2604 OID 24580)
-- Name: migrations id; Type: DEFAULT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.migrations ALTER COLUMN id SET DEFAULT nextval('carturesti_mic.migrations_id_seq'::regclass);


--
-- TOC entry 3442 (class 0 OID 24644)
-- Dependencies: 227
-- Data for Name: addresses; Type: TABLE DATA; Schema: carturesti_mic; Owner: carturar
--

COPY carturesti_mic.addresses (id, city, county, country, address_line) FROM stdin;
\.


--
-- TOC entry 3436 (class 0 OID 24615)
-- Dependencies: 221
-- Data for Name: auth; Type: TABLE DATA; Schema: carturesti_mic; Owner: carturar
--

COPY carturesti_mic.auth (id, token, user_id) FROM stdin;
\.


--
-- TOC entry 3440 (class 0 OID 24636)
-- Dependencies: 225
-- Data for Name: authors; Type: TABLE DATA; Schema: carturesti_mic; Owner: carturar
--

COPY carturesti_mic.authors (id, name) FROM stdin;
\.


--
-- TOC entry 3444 (class 0 OID 24652)
-- Dependencies: 229
-- Data for Name: books; Type: TABLE DATA; Schema: carturesti_mic; Owner: carturar
--

COPY carturesti_mic.books (id, title, price, genre_id, quantity) FROM stdin;
\.


--
-- TOC entry 3446 (class 0 OID 24665)
-- Dependencies: 231
-- Data for Name: books_authors; Type: TABLE DATA; Schema: carturesti_mic; Owner: carturar
--

COPY carturesti_mic.books_authors (id, book_id, author_id) FROM stdin;
\.


--
-- TOC entry 3452 (class 0 OID 24715)
-- Dependencies: 237
-- Data for Name: favourite_books; Type: TABLE DATA; Schema: carturesti_mic; Owner: carturar
--

COPY carturesti_mic.favourite_books (id, book_id, user_id) FROM stdin;
\.


--
-- TOC entry 3438 (class 0 OID 24628)
-- Dependencies: 223
-- Data for Name: genres; Type: TABLE DATA; Schema: carturesti_mic; Owner: carturar
--

COPY carturesti_mic.genres (id, name) FROM stdin;
\.


--
-- TOC entry 3432 (class 0 OID 24577)
-- Dependencies: 217
-- Data for Name: migrations; Type: TABLE DATA; Schema: carturesti_mic; Owner: carturar
--

COPY carturesti_mic.migrations (id, "timestamp", name) FROM stdin;
\.


--
-- TOC entry 3450 (class 0 OID 24699)
-- Dependencies: 235
-- Data for Name: order_products; Type: TABLE DATA; Schema: carturesti_mic; Owner: carturar
--

COPY carturesti_mic.order_products (id, order_id, book_id, quantity) FROM stdin;
\.


--
-- TOC entry 3448 (class 0 OID 24681)
-- Dependencies: 233
-- Data for Name: orders; Type: TABLE DATA; Schema: carturesti_mic; Owner: carturar
--

COPY carturesti_mic.orders (id, user_id, total, creation_date, status, address_id) FROM stdin;
\.


--
-- TOC entry 3434 (class 0 OID 24606)
-- Dependencies: 219
-- Data for Name: users; Type: TABLE DATA; Schema: carturesti_mic; Owner: carturar
--

COPY carturesti_mic.users (id, email, first_name, last_name, password, is_admin) FROM stdin;
\.


--
-- TOC entry 3459 (class 0 OID 0)
-- Dependencies: 226
-- Name: addresses_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: carturar
--

SELECT pg_catalog.setval('carturesti_mic.addresses_id_seq', 1, false);


--
-- TOC entry 3460 (class 0 OID 0)
-- Dependencies: 220
-- Name: auth_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: carturar
--

SELECT pg_catalog.setval('carturesti_mic.auth_id_seq', 1, false);


--
-- TOC entry 3461 (class 0 OID 0)
-- Dependencies: 224
-- Name: authors_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: carturar
--

SELECT pg_catalog.setval('carturesti_mic.authors_id_seq', 1, false);


--
-- TOC entry 3462 (class 0 OID 0)
-- Dependencies: 230
-- Name: books_authors_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: carturar
--

SELECT pg_catalog.setval('carturesti_mic.books_authors_id_seq', 1, false);


--
-- TOC entry 3463 (class 0 OID 0)
-- Dependencies: 228
-- Name: books_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: carturar
--

SELECT pg_catalog.setval('carturesti_mic.books_id_seq', 1, false);


--
-- TOC entry 3464 (class 0 OID 0)
-- Dependencies: 236
-- Name: favourite_books_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: carturar
--

SELECT pg_catalog.setval('carturesti_mic.favourite_books_id_seq', 1, false);


--
-- TOC entry 3465 (class 0 OID 0)
-- Dependencies: 222
-- Name: genres_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: carturar
--

SELECT pg_catalog.setval('carturesti_mic.genres_id_seq', 1, false);


--
-- TOC entry 3466 (class 0 OID 0)
-- Dependencies: 216
-- Name: migrations_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: carturar
--

SELECT pg_catalog.setval('carturesti_mic.migrations_id_seq', 1, false);


--
-- TOC entry 3467 (class 0 OID 0)
-- Dependencies: 234
-- Name: order_products_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: carturar
--

SELECT pg_catalog.setval('carturesti_mic.order_products_id_seq', 1, false);


--
-- TOC entry 3468 (class 0 OID 0)
-- Dependencies: 232
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: carturar
--

SELECT pg_catalog.setval('carturesti_mic.orders_id_seq', 1, false);


--
-- TOC entry 3469 (class 0 OID 0)
-- Dependencies: 218
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: carturar
--

SELECT pg_catalog.setval('carturesti_mic.users_id_seq', 1, false);


--
-- TOC entry 3257 (class 2606 OID 24584)
-- Name: migrations PK_8c82d7f526340ab734260ea46be; Type: CONSTRAINT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.migrations
    ADD CONSTRAINT "PK_8c82d7f526340ab734260ea46be" PRIMARY KEY (id);


--
-- TOC entry 3267 (class 2606 OID 24650)
-- Name: addresses addresses_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.addresses
    ADD CONSTRAINT addresses_pkey PRIMARY KEY (id);


--
-- TOC entry 3261 (class 2606 OID 24621)
-- Name: auth auth_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.auth
    ADD CONSTRAINT auth_pkey PRIMARY KEY (token, id);


--
-- TOC entry 3265 (class 2606 OID 24642)
-- Name: authors authors_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.authors
    ADD CONSTRAINT authors_pkey PRIMARY KEY (id);


--
-- TOC entry 3271 (class 2606 OID 24669)
-- Name: books_authors books_authors_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.books_authors
    ADD CONSTRAINT books_authors_pkey PRIMARY KEY (id);


--
-- TOC entry 3269 (class 2606 OID 24658)
-- Name: books books_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.books
    ADD CONSTRAINT books_pkey PRIMARY KEY (id);


--
-- TOC entry 3277 (class 2606 OID 24719)
-- Name: favourite_books favourite_books_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.favourite_books
    ADD CONSTRAINT favourite_books_pkey PRIMARY KEY (id);


--
-- TOC entry 3263 (class 2606 OID 24634)
-- Name: genres genres_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.genres
    ADD CONSTRAINT genres_pkey PRIMARY KEY (id);


--
-- TOC entry 3275 (class 2606 OID 24703)
-- Name: order_products order_products_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.order_products
    ADD CONSTRAINT order_products_pkey PRIMARY KEY (id);


--
-- TOC entry 3273 (class 2606 OID 24687)
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- TOC entry 3259 (class 2606 OID 24613)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3282 (class 2606 OID 24693)
-- Name: orders address_id_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.orders
    ADD CONSTRAINT address_id_fk FOREIGN KEY (address_id) REFERENCES carturesti_mic.addresses(id) ON DELETE CASCADE;


--
-- TOC entry 3280 (class 2606 OID 24675)
-- Name: books_authors author_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.books_authors
    ADD CONSTRAINT author_fk FOREIGN KEY (author_id) REFERENCES carturesti_mic.authors(id) ON DELETE CASCADE;


--
-- TOC entry 3281 (class 2606 OID 24670)
-- Name: books_authors book_id_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.books_authors
    ADD CONSTRAINT book_id_fk FOREIGN KEY (book_id) REFERENCES carturesti_mic.books(id) ON DELETE CASCADE;


--
-- TOC entry 3286 (class 2606 OID 24720)
-- Name: favourite_books fav_book_id_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.favourite_books
    ADD CONSTRAINT fav_book_id_fk FOREIGN KEY (book_id) REFERENCES carturesti_mic.books(id) ON DELETE CASCADE;


--
-- TOC entry 3287 (class 2606 OID 24725)
-- Name: favourite_books fav_user_id_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.favourite_books
    ADD CONSTRAINT fav_user_id_fk FOREIGN KEY (user_id) REFERENCES carturesti_mic.users(id) ON DELETE CASCADE;


--
-- TOC entry 3279 (class 2606 OID 24659)
-- Name: books genre_id_books_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.books
    ADD CONSTRAINT genre_id_books_fk FOREIGN KEY (genre_id) REFERENCES carturesti_mic.genres(id) ON DELETE CASCADE;


--
-- TOC entry 3284 (class 2606 OID 24704)
-- Name: order_products order_book_id_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.order_products
    ADD CONSTRAINT order_book_id_fk FOREIGN KEY (book_id) REFERENCES carturesti_mic.books(id) ON DELETE CASCADE;


--
-- TOC entry 3285 (class 2606 OID 24709)
-- Name: order_products order_id_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.order_products
    ADD CONSTRAINT order_id_fk FOREIGN KEY (order_id) REFERENCES carturesti_mic.orders(id) ON DELETE CASCADE;


--
-- TOC entry 3278 (class 2606 OID 24622)
-- Name: auth user_id_auth_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.auth
    ADD CONSTRAINT user_id_auth_fk FOREIGN KEY (user_id) REFERENCES carturesti_mic.users(id) ON DELETE CASCADE;


--
-- TOC entry 3283 (class 2606 OID 24688)
-- Name: orders user_id_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.orders
    ADD CONSTRAINT user_id_fk FOREIGN KEY (user_id) REFERENCES carturesti_mic.users(id) ON DELETE CASCADE;


-- Completed on 2023-12-19 20:58:52 EET

--
-- PostgreSQL database dump complete
--

