--
-- PostgreSQL database dump
--

-- Dumped from database version 16.0
-- Dumped by pg_dump version 16.0

-- Started on 2023-12-17 13:17:08

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 6 (class 2615 OID 16847)
-- Name: carturesti_mic; Type: SCHEMA; Schema: -; Owner: carturar
--

CREATE SCHEMA carturesti_mic;


ALTER SCHEMA carturesti_mic OWNER TO carturar;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 225 (class 1259 OID 16894)
-- Name: addresses; Type: TABLE; Schema: carturesti_mic; Owner: carturar
--

CREATE TABLE carturesti_mic.addresses (
    id integer NOT NULL,
    city character varying(512) NOT NULL,
    county character varying(512) NOT NULL,
    country character varying(512) NOT NULL,
    address_line character varying(512) NOT NULL
);


ALTER TABLE carturesti_mic.addresses OWNER TO carturar;

--
-- TOC entry 224 (class 1259 OID 16893)
-- Name: addresses_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE carturesti_mic.addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16857)
-- Name: auth; Type: TABLE; Schema: carturesti_mic; Owner: carturar
--

CREATE TABLE carturesti_mic.auth (
    id integer NOT NULL,
    token character varying(512) NOT NULL,
    user_id integer
);


ALTER TABLE carturesti_mic.auth OWNER TO carturar;

--
-- TOC entry 218 (class 1259 OID 16856)
-- Name: auth_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE carturesti_mic.auth ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.auth_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16878)
-- Name: authors; Type: TABLE; Schema: carturesti_mic; Owner: carturar
--

CREATE TABLE carturesti_mic.authors (
    id integer NOT NULL,
    name character varying(512) NOT NULL
);


ALTER TABLE carturesti_mic.authors OWNER TO carturar;

--
-- TOC entry 222 (class 1259 OID 16877)
-- Name: authors_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE carturesti_mic.authors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.authors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16902)
-- Name: books; Type: TABLE; Schema: carturesti_mic; Owner: carturar
--

CREATE TABLE carturesti_mic.books (
    id integer NOT NULL,
    title character varying(512) NOT NULL,
    price integer,
    genre_id integer,
    quantity integer
);


ALTER TABLE carturesti_mic.books OWNER TO carturar;

--
-- TOC entry 229 (class 1259 OID 16915)
-- Name: books_authors; Type: TABLE; Schema: carturesti_mic; Owner: postgres
--

CREATE TABLE carturesti_mic.books_authors (
    id integer NOT NULL,
    book_id integer NOT NULL,
    author_id integer NOT NULL
);


ALTER TABLE carturesti_mic.books_authors OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16914)
-- Name: books_authors_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE carturesti_mic.books_authors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.books_authors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16901)
-- Name: books_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE carturesti_mic.books ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.books_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 16968)
-- Name: favourite_books; Type: TABLE; Schema: carturesti_mic; Owner: postgres
--

CREATE TABLE carturesti_mic.favourite_books (
    id integer NOT NULL,
    book_id integer,
    user_id integer
);


ALTER TABLE carturesti_mic.favourite_books OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16967)
-- Name: favourite_books_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE carturesti_mic.favourite_books ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.favourite_books_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16870)
-- Name: genres; Type: TABLE; Schema: carturesti_mic; Owner: postgres
--

CREATE TABLE carturesti_mic.genres (
    id integer NOT NULL,
    name character varying(512) NOT NULL
);


ALTER TABLE carturesti_mic.genres OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16869)
-- Name: genres_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE carturesti_mic.genres ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.genres_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 16984)
-- Name: migrations; Type: TABLE; Schema: carturesti_mic; Owner: carturar
--

CREATE TABLE carturesti_mic.migrations (
    id integer NOT NULL,
    "timestamp" bigint NOT NULL,
    name character varying NOT NULL
);


ALTER TABLE carturesti_mic.migrations OWNER TO carturar;

--
-- TOC entry 236 (class 1259 OID 16983)
-- Name: migrations_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: carturar
--

CREATE SEQUENCE carturesti_mic.migrations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE carturesti_mic.migrations_id_seq OWNER TO carturar;

--
-- TOC entry 4942 (class 0 OID 0)
-- Dependencies: 236
-- Name: migrations_id_seq; Type: SEQUENCE OWNED BY; Schema: carturesti_mic; Owner: carturar
--

ALTER SEQUENCE carturesti_mic.migrations_id_seq OWNED BY carturesti_mic.migrations.id;


--
-- TOC entry 233 (class 1259 OID 16952)
-- Name: order_products; Type: TABLE; Schema: carturesti_mic; Owner: postgres
--

CREATE TABLE carturesti_mic.order_products (
    id integer NOT NULL,
    order_id integer,
    book_id integer,
    quantity integer
);


ALTER TABLE carturesti_mic.order_products OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16951)
-- Name: order_products_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE carturesti_mic.order_products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.order_products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16931)
-- Name: orders; Type: TABLE; Schema: carturesti_mic; Owner: postgres
--

CREATE TABLE carturesti_mic.orders (
    id integer NOT NULL,
    user_id integer NOT NULL,
    total integer NOT NULL,
    creation_date timestamp without time zone,
    address_id integer,
    status character varying(512) NOT NULL
);


ALTER TABLE carturesti_mic.orders OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16930)
-- Name: orders_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE carturesti_mic.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16849)
-- Name: users; Type: TABLE; Schema: carturesti_mic; Owner: postgres
--

CREATE TABLE carturesti_mic.users (
    id integer NOT NULL,
    email character varying(512) NOT NULL,
    first_name character varying(512) NOT NULL,
    last_name character varying(512) NOT NULL,
    password character varying(512) NOT NULL,
    is_admin boolean NOT NULL DEFAULT false
);


ALTER TABLE carturesti_mic.users OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16848)
-- Name: users_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE carturesti_mic.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4739 (class 2604 OID 16987)
-- Name: migrations id; Type: DEFAULT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.migrations ALTER COLUMN id SET DEFAULT nextval('carturesti_mic.migrations_id_seq'::regclass);


--
-- TOC entry 4924 (class 0 OID 16894)
-- Dependencies: 225
-- Data for Name: addresses; Type: TABLE DATA; Schema: carturesti_mic; Owner: carturar
--

COPY carturesti_mic.addresses (id, city, county, country, address_line) FROM stdin;
\.


--
-- TOC entry 4918 (class 0 OID 16857)
-- Dependencies: 219
-- Data for Name: auth; Type: TABLE DATA; Schema: carturesti_mic; Owner: carturar
--

COPY carturesti_mic.auth (id, token, user_id) FROM stdin;
7	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcwMjgwNzU3OH0.C-Le9XwWbPWhhrvIsCS_jMQV4J96GON5_ShCoec0Ixw	1
\.


--
-- TOC entry 4922 (class 0 OID 16878)
-- Dependencies: 223
-- Data for Name: authors; Type: TABLE DATA; Schema: carturesti_mic; Owner: carturar
--

COPY carturesti_mic.authors (id, name) FROM stdin;
\.


--
-- TOC entry 4926 (class 0 OID 16902)
-- Dependencies: 227
-- Data for Name: books; Type: TABLE DATA; Schema: carturesti_mic; Owner: carturar
--

COPY carturesti_mic.books (id, title, price, genre_id, quantity) FROM stdin;
\.


--
-- TOC entry 4928 (class 0 OID 16915)
-- Dependencies: 229
-- Data for Name: books_authors; Type: TABLE DATA; Schema: carturesti_mic; Owner: postgres
--

COPY carturesti_mic.books_authors (id, book_id, author_id) FROM stdin;
\.


--
-- TOC entry 4934 (class 0 OID 16968)
-- Dependencies: 235
-- Data for Name: favourite_books; Type: TABLE DATA; Schema: carturesti_mic; Owner: postgres
--

COPY carturesti_mic.favourite_books (id, book_id, user_id) FROM stdin;
\.


--
-- TOC entry 4920 (class 0 OID 16870)
-- Dependencies: 221
-- Data for Name: genres; Type: TABLE DATA; Schema: carturesti_mic; Owner: postgres
--

COPY carturesti_mic.genres (id, name) FROM stdin;
\.


--
-- TOC entry 4936 (class 0 OID 16984)
-- Dependencies: 237
-- Data for Name: migrations; Type: TABLE DATA; Schema: carturesti_mic; Owner: carturar
--

COPY carturesti_mic.migrations (id, "timestamp", name) FROM stdin;
\.


--
-- TOC entry 4932 (class 0 OID 16952)
-- Dependencies: 233
-- Data for Name: order_products; Type: TABLE DATA; Schema: carturesti_mic; Owner: postgres
--

COPY carturesti_mic.order_products (id, order_id, book_id, quantity) FROM stdin;
\.


--
-- TOC entry 4930 (class 0 OID 16931)
-- Dependencies: 231
-- Data for Name: orders; Type: TABLE DATA; Schema: carturesti_mic; Owner: postgres
--

COPY carturesti_mic.orders (id, user_id, total, creation_date, address_id, status) FROM stdin;
\.


--
-- TOC entry 4916 (class 0 OID 16849)
-- Dependencies: 217
-- Data for Name: users; Type: TABLE DATA; Schema: carturesti_mic; Owner: postgres
--

COPY carturesti_mic.users (id, email, first_name, last_name, password) FROM stdin;
1	alex.olaru@gmail.com	Alexandru	Olaru	$2b$10$6iE6KgVPRI0r3ZH.SY/acOYDMpZgWs6jxYkKb.l7izhnT5cOvCh9.
\.


--
-- TOC entry 4943 (class 0 OID 0)
-- Dependencies: 224
-- Name: addresses_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: carturar
--

SELECT pg_catalog.setval('carturesti_mic.addresses_id_seq', 1, false);


--
-- TOC entry 4944 (class 0 OID 0)
-- Dependencies: 218
-- Name: auth_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: carturar
--

SELECT pg_catalog.setval('carturesti_mic.auth_id_seq', 8, true);


--
-- TOC entry 4945 (class 0 OID 0)
-- Dependencies: 222
-- Name: authors_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: carturar
--

SELECT pg_catalog.setval('carturesti_mic.authors_id_seq', 1, false);


--
-- TOC entry 4946 (class 0 OID 0)
-- Dependencies: 228
-- Name: books_authors_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: postgres
--

SELECT pg_catalog.setval('carturesti_mic.books_authors_id_seq', 1, false);


--
-- TOC entry 4947 (class 0 OID 0)
-- Dependencies: 226
-- Name: books_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: carturar
--

SELECT pg_catalog.setval('carturesti_mic.books_id_seq', 1, false);


--
-- TOC entry 4948 (class 0 OID 0)
-- Dependencies: 234
-- Name: favourite_books_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: postgres
--

SELECT pg_catalog.setval('carturesti_mic.favourite_books_id_seq', 1, false);


--
-- TOC entry 4949 (class 0 OID 0)
-- Dependencies: 220
-- Name: genres_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: postgres
--

SELECT pg_catalog.setval('carturesti_mic.genres_id_seq', 1, false);


--
-- TOC entry 4950 (class 0 OID 0)
-- Dependencies: 236
-- Name: migrations_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: carturar
--

SELECT pg_catalog.setval('carturesti_mic.migrations_id_seq', 1, false);


--
-- TOC entry 4951 (class 0 OID 0)
-- Dependencies: 232
-- Name: order_products_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: postgres
--

SELECT pg_catalog.setval('carturesti_mic.order_products_id_seq', 1, false);


--
-- TOC entry 4952 (class 0 OID 0)
-- Dependencies: 230
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: postgres
--

SELECT pg_catalog.setval('carturesti_mic.orders_id_seq', 1, false);


--
-- TOC entry 4953 (class 0 OID 0)
-- Dependencies: 216
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: postgres
--

SELECT pg_catalog.setval('carturesti_mic.users_id_seq', 1, true);


--
-- TOC entry 4761 (class 2606 OID 16991)
-- Name: migrations PK_8c82d7f526340ab734260ea46be; Type: CONSTRAINT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.migrations
    ADD CONSTRAINT "PK_8c82d7f526340ab734260ea46be" PRIMARY KEY (id);


--
-- TOC entry 4749 (class 2606 OID 16900)
-- Name: addresses addresses_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.addresses
    ADD CONSTRAINT addresses_pkey PRIMARY KEY (id);


--
-- TOC entry 4743 (class 2606 OID 16863)
-- Name: auth auth_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.auth
    ADD CONSTRAINT auth_pkey PRIMARY KEY (token, id);


--
-- TOC entry 4747 (class 2606 OID 16884)
-- Name: authors authors_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.authors
    ADD CONSTRAINT authors_pkey PRIMARY KEY (id);


--
-- TOC entry 4753 (class 2606 OID 16919)
-- Name: books_authors books_authors_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.books_authors
    ADD CONSTRAINT books_authors_pkey PRIMARY KEY (id);


--
-- TOC entry 4751 (class 2606 OID 16908)
-- Name: books books_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.books
    ADD CONSTRAINT books_pkey PRIMARY KEY (id);


--
-- TOC entry 4759 (class 2606 OID 16972)
-- Name: favourite_books favourite_books_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.favourite_books
    ADD CONSTRAINT favourite_books_pkey PRIMARY KEY (id);


--
-- TOC entry 4745 (class 2606 OID 16876)
-- Name: genres genres_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.genres
    ADD CONSTRAINT genres_pkey PRIMARY KEY (id);


--
-- TOC entry 4757 (class 2606 OID 16956)
-- Name: order_products order_products_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.order_products
    ADD CONSTRAINT order_products_pkey PRIMARY KEY (id);


--
-- TOC entry 4755 (class 2606 OID 16935)
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- TOC entry 4741 (class 2606 OID 16855)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4766 (class 2606 OID 16946)
-- Name: orders address_id_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.orders
    ADD CONSTRAINT address_id_fk FOREIGN KEY (address_id) REFERENCES carturesti_mic.addresses(id) ON DELETE CASCADE;


--
-- TOC entry 4764 (class 2606 OID 16925)
-- Name: books_authors author_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.books_authors
    ADD CONSTRAINT author_fk FOREIGN KEY (author_id) REFERENCES carturesti_mic.authors(id) ON DELETE CASCADE;


--
-- TOC entry 4765 (class 2606 OID 16920)
-- Name: books_authors book_id_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.books_authors
    ADD CONSTRAINT book_id_fk FOREIGN KEY (book_id) REFERENCES carturesti_mic.books(id) ON DELETE CASCADE;


--
-- TOC entry 4770 (class 2606 OID 16973)
-- Name: favourite_books fav_book_id_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.favourite_books
    ADD CONSTRAINT fav_book_id_fk FOREIGN KEY (book_id) REFERENCES carturesti_mic.books(id) ON DELETE CASCADE;


--
-- TOC entry 4771 (class 2606 OID 16978)
-- Name: favourite_books fav_user_id_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.favourite_books
    ADD CONSTRAINT fav_user_id_fk FOREIGN KEY (user_id) REFERENCES carturesti_mic.users(id) ON DELETE CASCADE;


--
-- TOC entry 4763 (class 2606 OID 16909)
-- Name: books genre_id_books_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.books
    ADD CONSTRAINT genre_id_books_fk FOREIGN KEY (genre_id) REFERENCES carturesti_mic.genres(id) ON DELETE CASCADE;


--
-- TOC entry 4768 (class 2606 OID 16957)
-- Name: order_products order_book_id_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.order_products
    ADD CONSTRAINT order_book_id_fk FOREIGN KEY (book_id) REFERENCES carturesti_mic.books(id) ON DELETE CASCADE;


--
-- TOC entry 4769 (class 2606 OID 16962)
-- Name: order_products order_id_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.order_products
    ADD CONSTRAINT order_id_fk FOREIGN KEY (order_id) REFERENCES carturesti_mic.orders(id) ON DELETE CASCADE;


--
-- TOC entry 4762 (class 2606 OID 16864)
-- Name: auth user_id_auth_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: carturar
--

ALTER TABLE ONLY carturesti_mic.auth
    ADD CONSTRAINT user_id_auth_fk FOREIGN KEY (user_id) REFERENCES carturesti_mic.users(id) ON DELETE CASCADE;


--
-- TOC entry 4767 (class 2606 OID 16936)
-- Name: orders user_id_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.orders
    ADD CONSTRAINT user_id_fk FOREIGN KEY (user_id) REFERENCES carturesti_mic.users(id) ON DELETE CASCADE;


-- Completed on 2023-12-17 13:17:09

--
-- PostgreSQL database dump complete
--

