--
-- PostgreSQL database dump
--

-- Dumped from database version 16.0
-- Dumped by pg_dump version 16.0

-- Started on 2023-12-09 20:46:39

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 7 (class 2615 OID 16691)
-- Name: carturesti_mic; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA carturesti_mic;


ALTER SCHEMA carturesti_mic OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 239 (class 1259 OID 16754)
-- Name: addresses; Type: TABLE; Schema: carturesti_mic; Owner: postgres
--

CREATE TABLE carturesti_mic.addresses (
    id integer NOT NULL,
    city character varying(512) NOT NULL,
    county character varying(512) NOT NULL,
    country character varying(512) NOT NULL,
    address_line character varying(512) NOT NULL
);


ALTER TABLE carturesti_mic.addresses OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 16753)
-- Name: addresses_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE carturesti_mic.addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16717)
-- Name: auth; Type: TABLE; Schema: carturesti_mic; Owner: postgres
--

CREATE TABLE carturesti_mic.auth (
    id integer NOT NULL,
    token character varying(512) NOT NULL,
    user_id integer
);


ALTER TABLE carturesti_mic.auth OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16716)
-- Name: auth_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE carturesti_mic.auth ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.auth_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 16738)
-- Name: authors; Type: TABLE; Schema: carturesti_mic; Owner: postgres
--

CREATE TABLE carturesti_mic.authors (
    id integer NOT NULL,
    name character varying(512) NOT NULL
);


ALTER TABLE carturesti_mic.authors OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16737)
-- Name: authors_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE carturesti_mic.authors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.authors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 16762)
-- Name: books; Type: TABLE; Schema: carturesti_mic; Owner: postgres
--

CREATE TABLE carturesti_mic.books (
    id integer NOT NULL,
    title character varying(512) NOT NULL,
    price integer,
    genre_id integer,
    quantity integer
);


ALTER TABLE carturesti_mic.books OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 16775)
-- Name: books_authors; Type: TABLE; Schema: carturesti_mic; Owner: postgres
--

CREATE TABLE carturesti_mic.books_authors (
    id integer NOT NULL,
    book_id integer NOT NULL,
    author_id integer NOT NULL
);


ALTER TABLE carturesti_mic.books_authors OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 16774)
-- Name: books_authors_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE carturesti_mic.books_authors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.books_authors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 16761)
-- Name: books_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE carturesti_mic.books ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.books_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 16828)
-- Name: favourite_books; Type: TABLE; Schema: carturesti_mic; Owner: postgres
--

CREATE TABLE carturesti_mic.favourite_books (
    id integer NOT NULL,
    book_id integer,
    user_id integer
);


ALTER TABLE carturesti_mic.favourite_books OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 16827)
-- Name: favourite_books_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE carturesti_mic.favourite_books ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.favourite_books_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16730)
-- Name: genres; Type: TABLE; Schema: carturesti_mic; Owner: postgres
--

CREATE TABLE carturesti_mic.genres (
    id integer NOT NULL,
    name character varying(512) NOT NULL
);


ALTER TABLE carturesti_mic.genres OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16729)
-- Name: genres_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE carturesti_mic.genres ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.genres_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 16812)
-- Name: order_products; Type: TABLE; Schema: carturesti_mic; Owner: postgres
--

CREATE TABLE carturesti_mic.order_products (
    id integer NOT NULL,
    order_id integer,
    book_id integer,
    quantity integer
);


ALTER TABLE carturesti_mic.order_products OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 16811)
-- Name: order_products_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE carturesti_mic.order_products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.order_products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 16746)
-- Name: order_statuses; Type: TABLE; Schema: carturesti_mic; Owner: postgres
--

CREATE TABLE carturesti_mic.order_statuses (
    id integer NOT NULL,
    name character varying(512) NOT NULL
);


ALTER TABLE carturesti_mic.order_statuses OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 16745)
-- Name: order_statuses_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE carturesti_mic.order_statuses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.order_statuses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 16791)
-- Name: orders; Type: TABLE; Schema: carturesti_mic; Owner: postgres
--

CREATE TABLE carturesti_mic.orders (
    id integer NOT NULL,
    user_id integer NOT NULL,
    total integer NOT NULL,
    creation_date timestamp without time zone,
    status_id integer,
    address_id integer
);


ALTER TABLE carturesti_mic.orders OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 16790)
-- Name: orders_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE carturesti_mic.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16709)
-- Name: users; Type: TABLE; Schema: carturesti_mic; Owner: postgres
--

CREATE TABLE carturesti_mic.users (
    id integer NOT NULL,
    email character varying(512) NOT NULL,
    first_name character varying(512) NOT NULL,
    last_name character varying(512) NOT NULL,
    password character varying(512) NOT NULL
);


ALTER TABLE carturesti_mic.users OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16708)
-- Name: users_id_seq; Type: SEQUENCE; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE carturesti_mic.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carturesti_mic.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4954 (class 0 OID 16754)
-- Dependencies: 239
-- Data for Name: addresses; Type: TABLE DATA; Schema: carturesti_mic; Owner: postgres
--

COPY carturesti_mic.addresses (id, city, county, country, address_line) FROM stdin;
\.


--
-- TOC entry 4946 (class 0 OID 16717)
-- Dependencies: 231
-- Data for Name: auth; Type: TABLE DATA; Schema: carturesti_mic; Owner: postgres
--

COPY carturesti_mic.auth (id, token, user_id) FROM stdin;
\.


--
-- TOC entry 4950 (class 0 OID 16738)
-- Dependencies: 235
-- Data for Name: authors; Type: TABLE DATA; Schema: carturesti_mic; Owner: postgres
--

COPY carturesti_mic.authors (id, name) FROM stdin;
\.


--
-- TOC entry 4956 (class 0 OID 16762)
-- Dependencies: 241
-- Data for Name: books; Type: TABLE DATA; Schema: carturesti_mic; Owner: postgres
--

COPY carturesti_mic.books (id, title, price, genre_id, quantity) FROM stdin;
\.


--
-- TOC entry 4958 (class 0 OID 16775)
-- Dependencies: 243
-- Data for Name: books_authors; Type: TABLE DATA; Schema: carturesti_mic; Owner: postgres
--

COPY carturesti_mic.books_authors (id, book_id, author_id) FROM stdin;
\.


--
-- TOC entry 4964 (class 0 OID 16828)
-- Dependencies: 249
-- Data for Name: favourite_books; Type: TABLE DATA; Schema: carturesti_mic; Owner: postgres
--

COPY carturesti_mic.favourite_books (id, book_id, user_id) FROM stdin;
\.


--
-- TOC entry 4948 (class 0 OID 16730)
-- Dependencies: 233
-- Data for Name: genres; Type: TABLE DATA; Schema: carturesti_mic; Owner: postgres
--

COPY carturesti_mic.genres (id, name) FROM stdin;
\.


--
-- TOC entry 4962 (class 0 OID 16812)
-- Dependencies: 247
-- Data for Name: order_products; Type: TABLE DATA; Schema: carturesti_mic; Owner: postgres
--

COPY carturesti_mic.order_products (id, order_id, book_id, quantity) FROM stdin;
\.


--
-- TOC entry 4952 (class 0 OID 16746)
-- Dependencies: 237
-- Data for Name: order_statuses; Type: TABLE DATA; Schema: carturesti_mic; Owner: postgres
--

COPY carturesti_mic.order_statuses (id, name) FROM stdin;
\.


--
-- TOC entry 4960 (class 0 OID 16791)
-- Dependencies: 245
-- Data for Name: orders; Type: TABLE DATA; Schema: carturesti_mic; Owner: postgres
--

COPY carturesti_mic.orders (id, user_id, total, creation_date, status_id, address_id) FROM stdin;
\.


--
-- TOC entry 4944 (class 0 OID 16709)
-- Dependencies: 229
-- Data for Name: users; Type: TABLE DATA; Schema: carturesti_mic; Owner: postgres
--

COPY carturesti_mic.users (id, email, first_name, last_name, password) FROM stdin;
\.


--
-- TOC entry 4970 (class 0 OID 0)
-- Dependencies: 238
-- Name: addresses_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: postgres
--

SELECT pg_catalog.setval('carturesti_mic.addresses_id_seq', 1, false);


--
-- TOC entry 4971 (class 0 OID 0)
-- Dependencies: 230
-- Name: auth_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: postgres
--

SELECT pg_catalog.setval('carturesti_mic.auth_id_seq', 1, false);


--
-- TOC entry 4972 (class 0 OID 0)
-- Dependencies: 234
-- Name: authors_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: postgres
--

SELECT pg_catalog.setval('carturesti_mic.authors_id_seq', 1, false);


--
-- TOC entry 4973 (class 0 OID 0)
-- Dependencies: 242
-- Name: books_authors_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: postgres
--

SELECT pg_catalog.setval('carturesti_mic.books_authors_id_seq', 1, false);


--
-- TOC entry 4974 (class 0 OID 0)
-- Dependencies: 240
-- Name: books_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: postgres
--

SELECT pg_catalog.setval('carturesti_mic.books_id_seq', 1, false);


--
-- TOC entry 4975 (class 0 OID 0)
-- Dependencies: 248
-- Name: favourite_books_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: postgres
--

SELECT pg_catalog.setval('carturesti_mic.favourite_books_id_seq', 1, false);


--
-- TOC entry 4976 (class 0 OID 0)
-- Dependencies: 232
-- Name: genres_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: postgres
--

SELECT pg_catalog.setval('carturesti_mic.genres_id_seq', 1, false);


--
-- TOC entry 4977 (class 0 OID 0)
-- Dependencies: 246
-- Name: order_products_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: postgres
--

SELECT pg_catalog.setval('carturesti_mic.order_products_id_seq', 1, false);


--
-- TOC entry 4978 (class 0 OID 0)
-- Dependencies: 236
-- Name: order_statuses_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: postgres
--

SELECT pg_catalog.setval('carturesti_mic.order_statuses_id_seq', 1, false);


--
-- TOC entry 4979 (class 0 OID 0)
-- Dependencies: 244
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: postgres
--

SELECT pg_catalog.setval('carturesti_mic.orders_id_seq', 1, false);


--
-- TOC entry 4980 (class 0 OID 0)
-- Dependencies: 228
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: carturesti_mic; Owner: postgres
--

SELECT pg_catalog.setval('carturesti_mic.users_id_seq', 1, false);


--
-- TOC entry 4778 (class 2606 OID 16760)
-- Name: addresses addresses_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.addresses
    ADD CONSTRAINT addresses_pkey PRIMARY KEY (id);


--
-- TOC entry 4770 (class 2606 OID 16723)
-- Name: auth auth_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.auth
    ADD CONSTRAINT auth_pkey PRIMARY KEY (token, id);


--
-- TOC entry 4774 (class 2606 OID 16744)
-- Name: authors authors_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.authors
    ADD CONSTRAINT authors_pkey PRIMARY KEY (id);


--
-- TOC entry 4782 (class 2606 OID 16779)
-- Name: books_authors books_authors_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.books_authors
    ADD CONSTRAINT books_authors_pkey PRIMARY KEY (id);


--
-- TOC entry 4780 (class 2606 OID 16768)
-- Name: books books_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.books
    ADD CONSTRAINT books_pkey PRIMARY KEY (id);


--
-- TOC entry 4788 (class 2606 OID 16832)
-- Name: favourite_books favourite_books_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.favourite_books
    ADD CONSTRAINT favourite_books_pkey PRIMARY KEY (id);


--
-- TOC entry 4772 (class 2606 OID 16736)
-- Name: genres genres_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.genres
    ADD CONSTRAINT genres_pkey PRIMARY KEY (id);


--
-- TOC entry 4786 (class 2606 OID 16816)
-- Name: order_products order_products_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.order_products
    ADD CONSTRAINT order_products_pkey PRIMARY KEY (id);


--
-- TOC entry 4776 (class 2606 OID 16752)
-- Name: order_statuses order_statuses_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.order_statuses
    ADD CONSTRAINT order_statuses_pkey PRIMARY KEY (id);


--
-- TOC entry 4784 (class 2606 OID 16795)
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- TOC entry 4768 (class 2606 OID 16715)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4793 (class 2606 OID 16806)
-- Name: orders address_id_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.orders
    ADD CONSTRAINT address_id_fk FOREIGN KEY (address_id) REFERENCES carturesti_mic.addresses(id) ON DELETE CASCADE;


--
-- TOC entry 4791 (class 2606 OID 16785)
-- Name: books_authors author_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.books_authors
    ADD CONSTRAINT author_fk FOREIGN KEY (author_id) REFERENCES carturesti_mic.authors(id) ON DELETE CASCADE;


--
-- TOC entry 4792 (class 2606 OID 16780)
-- Name: books_authors book_id_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.books_authors
    ADD CONSTRAINT book_id_fk FOREIGN KEY (book_id) REFERENCES carturesti_mic.books(id) ON DELETE CASCADE;


--
-- TOC entry 4798 (class 2606 OID 16833)
-- Name: favourite_books fav_book_id_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.favourite_books
    ADD CONSTRAINT fav_book_id_fk FOREIGN KEY (book_id) REFERENCES carturesti_mic.books(id) ON DELETE CASCADE;


--
-- TOC entry 4799 (class 2606 OID 16838)
-- Name: favourite_books fav_user_id_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.favourite_books
    ADD CONSTRAINT fav_user_id_fk FOREIGN KEY (user_id) REFERENCES carturesti_mic.users(id) ON DELETE CASCADE;


--
-- TOC entry 4790 (class 2606 OID 16769)
-- Name: books genre_id_books_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.books
    ADD CONSTRAINT genre_id_books_fk FOREIGN KEY (genre_id) REFERENCES carturesti_mic.genres(id) ON DELETE CASCADE;


--
-- TOC entry 4796 (class 2606 OID 16817)
-- Name: order_products order_book_id_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.order_products
    ADD CONSTRAINT order_book_id_fk FOREIGN KEY (book_id) REFERENCES carturesti_mic.books(id) ON DELETE CASCADE;


--
-- TOC entry 4797 (class 2606 OID 16822)
-- Name: order_products order_id_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.order_products
    ADD CONSTRAINT order_id_fk FOREIGN KEY (order_id) REFERENCES carturesti_mic.orders(id) ON DELETE CASCADE;


--
-- TOC entry 4794 (class 2606 OID 16801)
-- Name: orders order_statuses_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.orders
    ADD CONSTRAINT order_statuses_fk FOREIGN KEY (status_id) REFERENCES carturesti_mic.order_statuses(id) ON DELETE CASCADE;


--
-- TOC entry 4789 (class 2606 OID 16724)
-- Name: auth user_id_auth_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.auth
    ADD CONSTRAINT user_id_auth_fk FOREIGN KEY (user_id) REFERENCES carturesti_mic.users(id) ON DELETE CASCADE;


--
-- TOC entry 4795 (class 2606 OID 16796)
-- Name: orders user_id_fk; Type: FK CONSTRAINT; Schema: carturesti_mic; Owner: postgres
--

ALTER TABLE ONLY carturesti_mic.orders
    ADD CONSTRAINT user_id_fk FOREIGN KEY (user_id) REFERENCES carturesti_mic.users(id) ON DELETE CASCADE;


-- Completed on 2023-12-09 20:46:39

--
-- PostgreSQL database dump complete
--

