CREATE TABLE "carturesti_mic"."users" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
  "email"  character varying(512) COLLATE pg_catalog."default" NOT NULL,
  "first_name" character varying(512) COLLATE pg_catalog."default" NOT NULL,
  "last_name" character varying(512) COLLATE pg_catalog."default" NOT NULL,
  "password" character varying(512) COLLATE pg_catalog."default" NOT NULL,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE "carturesti_mic"."auth" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
  "token" character varying(512) COLLATE pg_catalog."default" NOT NULL,
  "user_id" integer,
  CONSTRAINT auth_pkey PRIMARY KEY (token, id),
  CONSTRAINT user_id_auth_fk FOREIGN KEY (user_id)
      REFERENCES "carturesti_mic"."users" (id) MATCH SIMPLE
      ON UPDATE NO ACTION
      ON DELETE CASCADE
);

CREATE TABLE "carturesti_mic"."genres" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
  "name"  character varying(512) COLLATE pg_catalog."default" NOT NULL,
  CONSTRAINT genres_pkey PRIMARY KEY (id)
);

CREATE TABLE "carturesti_mic"."authors" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
  "name"  character varying(512) COLLATE pg_catalog."default" NOT NULL,
  CONSTRAINT authors_pkey PRIMARY KEY (id)
);

CREATE TABLE "carturesti_mic"."addresses" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
  "city" character varying(512) COLLATE pg_catalog."default" NOT NULL,
  "county" character varying(512) COLLATE pg_catalog."default" NOT NULL,
  "country" character varying(512) COLLATE pg_catalog."default" NOT NULL,
  "address_line" character varying(512) COLLATE pg_catalog."default" NOT NULL,
  CONSTRAINT addresses_pkey PRIMARY KEY (id)
);

CREATE TABLE "carturesti_mic"."books" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
  "title"  character varying(512) COLLATE pg_catalog."default" NOT NULL,
  "price" integer,
  "genre_id" integer,
  "quantity" integer,
  CONSTRAINT books_pkey PRIMARY KEY (id),
  CONSTRAINT genre_id_books_fk FOREIGN KEY (genre_id)
      REFERENCES "carturesti_mic"."genres" (id) MATCH SIMPLE
      ON UPDATE NO ACTION
      ON DELETE CASCADE
);

CREATE TABLE "carturesti_mic"."books_authors" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
  "book_id" integer  NOT NULL,
  "author_id" integer  NOT NULL,
  CONSTRAINT books_authors_pkey PRIMARY KEY (id),
  CONSTRAINT book_id_fk FOREIGN KEY (book_id)
    REFERENCES "carturesti_mic"."books" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE,
  CONSTRAINT author_fk FOREIGN KEY (author_id)
    REFERENCES "carturesti_mic"."authors" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
);

CREATE TABLE "carturesti_mic"."orders" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
  "user_id" integer  NOT NULL,
  "total" integer  NOT NULL,
  "creation_date" timestamp,
  "status" character varying(512) COLLATE pg_catalog."default" NOT NULL,
  "address_id" integer,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT user_id_fk FOREIGN KEY (user_id)
    REFERENCES "carturesti_mic"."users" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE,
  CONSTRAINT address_id_fk FOREIGN KEY (address_id)
    REFERENCES "carturesti_mic"."addresses" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
);

CREATE TABLE "carturesti_mic"."order_products" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
  "order_id" integer,
  "book_id" integer,
  "quantity" integer,
  CONSTRAINT order_products_pkey PRIMARY KEY (id),
  CONSTRAINT order_book_id_fk FOREIGN KEY (book_id)
    REFERENCES "carturesti_mic"."books" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE,
  CONSTRAINT order_id_fk FOREIGN KEY (order_id)
    REFERENCES "carturesti_mic"."orders" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
);

CREATE TABLE "carturesti_mic"."favourite_books" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
  "book_id" integer,
  "user_id" integer,
  CONSTRAINT favourite_books_pkey PRIMARY KEY (id),
  CONSTRAINT fav_book_id_fk FOREIGN KEY (book_id)
    REFERENCES "carturesti_mic"."books" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE,
  CONSTRAINT fav_user_id_fk FOREIGN KEY (user_id)
    REFERENCES "carturesti_mic"."users" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
);